/**
 * Seed dataset of high-ticket Bangalore local businesses without websites
 * Ready for immediate outreach & testing
 */

const SEED_LEADS = [
  {
    id: 'blr-lead-001',
    name: 'Smile Craft Dental Studio & Implant Centre',
    category: 'Dental Clinic',
    nicheId: 'dental-clinics',
    locality: 'Koramangala',
    zone: 'South',
    address: '80 Feet Road, 4th Block, Koramangala, Bengaluru, Karnataka 560034',
    phone: '+919845123049',
    rawPhone: '098451 23049',
    rating: 4.8,
    reviewsCount: 142,
    website: null,
    websiteStatus: 'NO_WEBSITE', // NO_WEBSITE, SOCIAL_ONLY, HAS_WEBSITE
    googleMapsUrl: 'https://maps.google.com/?q=Smile+Craft+Dental+Studio+Koramangala+Bangalore',
    opportunityScore: 95,
    crmStatus: 'NEW', // NEW, CONTACTED, PITCH_SENT, MEETING_BOOKED, CLOSED_WON, REJECTED
    notes: 'High review count in 4th block. Urgent need for smile makeover showcase & appointment booking.',
    createdAt: new Date().toISOString()
  },
  {
    id: 'blr-lead-002',
    name: 'Aura Luxe Unisex Salon & Bridal Studio',
    category: 'Beauty Salon & Spa',
    nicheId: 'salons-spas',
    locality: 'Indiranagar',
    zone: 'East',
    address: '100 Feet Road, HAL 2nd Stage, Indiranagar, Bengaluru, Karnataka 560038',
    phone: '+919900887123',
    rawPhone: '099008 87123',
    rating: 4.7,
    reviewsCount: 98,
    website: 'https://instagram.com/auraluxesalon_blr',
    websiteStatus: 'SOCIAL_ONLY',
    googleMapsUrl: 'https://maps.google.com/?q=Aura+Luxe+Salon+Indiranagar+Bangalore',
    opportunityScore: 92,
    crmStatus: 'NEW',
    notes: 'Only has an Instagram link on Google Maps. Needs rate card & bridal package booking site.',
    createdAt: new Date().toISOString()
  },
  {
    id: 'blr-lead-003',
    name: 'Vruksha Living Interiors & Modular Spaces',
    category: 'Interior Designer',
    nicheId: 'interior-designers',
    locality: 'HSR Layout',
    zone: 'South',
    address: 'Sector 2, 27th Main Road, HSR Layout, Bengaluru, Karnataka 560102',
    phone: '+919731298450',
    rawPhone: '097312 98450',
    rating: 4.9,
    reviewsCount: 64,
    website: null,
    websiteStatus: 'NO_WEBSITE',
    googleMapsUrl: 'https://maps.google.com/?q=Vruksha+Living+Interiors+HSR+Layout+Bangalore',
    opportunityScore: 98,
    crmStatus: 'NEW',
    notes: 'High-ticket interior design studio in HSR. Losing clients because no 3D portfolio site.',
    createdAt: new Date().toISOString()
  },
  {
    id: 'blr-lead-004',
    name: 'DermaGlow Skin & Hair Laser Clinic',
    category: 'Dermatologist Clinic',
    nicheId: 'dermatology-skin',
    locality: 'Whitefield',
    zone: 'East',
    address: 'ECC Road, near ITPL, Whitefield, Bengaluru, Karnataka 560066',
    phone: '+919886341209',
    rawPhone: '098863 41209',
    rating: 4.6,
    reviewsCount: 88,
    website: null,
    websiteStatus: 'NO_WEBSITE',
    googleMapsUrl: 'https://maps.google.com/?q=DermaGlow+Skin+Clinic+Whitefield+Bangalore',
    opportunityScore: 94,
    crmStatus: 'NEW',
    notes: 'Prime ITPL techie clientele. Needs online consultation & doctor schedule.',
    createdAt: new Date().toISOString()
  },
  {
    id: 'blr-lead-005',
    name: 'Paws & Claws 24/7 Veterinary Hospital',
    category: 'Pet Clinic',
    nicheId: 'pet-clinics',
    locality: 'Jayanagar',
    zone: 'South',
    address: '9th Main Road, 4th Block, Jayanagar, Bengaluru, Karnataka 560011',
    phone: '+919448109872',
    rawPhone: '094481 09872',
    rating: 4.8,
    reviewsCount: 175,
    website: 'https://facebook.com/pawsandclawsblr',
    websiteStatus: 'SOCIAL_ONLY',
    googleMapsUrl: 'https://maps.google.com/?q=Paws+Claws+Pet+Clinic+Jayanagar+Bangalore',
    opportunityScore: 96,
    crmStatus: 'NEW',
    notes: '175+ reviews, 24/7 service. Only uses Facebook. Huge opportunity for emergency direct site.',
    createdAt: new Date().toISOString()
  },
  {
    id: 'blr-lead-006',
    name: 'Shree Sanjeevani Ayurvedic Panchakarma Care',
    category: 'Ayurvedic Center',
    nicheId: 'ayurveda-wellness',
    locality: 'JP Nagar',
    zone: 'South',
    address: '24th Main, 5th Phase, JP Nagar, Bengaluru, Karnataka 560078',
    phone: '+919611234890',
    rawPhone: '096112 34890',
    rating: 4.7,
    reviewsCount: 52,
    website: null,
    websiteStatus: 'NO_WEBSITE',
    googleMapsUrl: 'https://maps.google.com/?q=Sanjeevani+Ayurvedic+Care+JP+Nagar+Bangalore',
    opportunityScore: 89,
    crmStatus: 'NEW',
    notes: 'Offers traditional wellness packages. Pitch Panchakarma therapy package booking site.',
    createdAt: new Date().toISOString()
  },
  {
    id: 'blr-lead-007',
    name: 'Apex Precision Ceramic Detailing Studio',
    category: 'Car Detailing Studio',
    nicheId: 'car-detailing',
    locality: 'Kalyan Nagar / Kammanahalli',
    zone: 'East',
    address: 'CMR Road, HRBR Layout 2nd Block, Kalyan Nagar, Bengaluru, Karnataka 560043',
    phone: '+919844019283',
    rawPhone: '098440 19283',
    rating: 4.9,
    reviewsCount: 110,
    website: null,
    websiteStatus: 'NO_WEBSITE',
    googleMapsUrl: 'https://maps.google.com/?q=Apex+Ceramic+Detailing+Kalyan+Nagar+Bangalore',
    opportunityScore: 97,
    crmStatus: 'NEW',
    notes: 'Ceramic coating & PPF deals ₹30k+. Zero website. Show high-gloss visual gallery.',
    createdAt: new Date().toISOString()
  },
  {
    id: 'blr-lead-008',
    name: 'Grand Royal Caterers & Event Specialists',
    category: 'Caterer & Wedding Planner',
    nicheId: 'wedding-caterers',
    locality: 'Malleshwaram',
    zone: 'Central',
    address: 'Sampige Road, 8th Cross, Malleshwaram, Bengaluru, Karnataka 560003',
    phone: '+919980556712',
    rawPhone: '099805 56712',
    rating: 4.6,
    reviewsCount: 84,
    website: null,
    websiteStatus: 'NO_WEBSITE',
    googleMapsUrl: 'https://maps.google.com/?q=Grand+Royal+Caterers+Malleshwaram+Bangalore',
    opportunityScore: 91,
    crmStatus: 'NEW',
    notes: 'High volume wedding caterer. Pitch digital interactive menu & guest pricing calculator.',
    createdAt: new Date().toISOString()
  },
  {
    id: 'blr-lead-009',
    name: 'Kumble & Associates Chartered Accountants',
    category: 'CA & Tax Consultant',
    nicheId: 'ca-tax-consultants',
    locality: 'MG Road / Brigade Road',
    zone: 'Central',
    address: 'Residency Road, near Brigade Towers, Bengaluru, Karnataka 560025',
    phone: '+919845009182',
    rawPhone: '098450 09182',
    rating: 4.8,
    reviewsCount: 39,
    website: null,
    websiteStatus: 'NO_WEBSITE',
    googleMapsUrl: 'https://maps.google.com/?q=Kumble+Associates+CA+MG+Road+Bangalore',
    opportunityScore: 88,
    crmStatus: 'NEW',
    notes: 'Corporate taxation & audit firm in CBD. Needs authoritative corporate presence.',
    createdAt: new Date().toISOString()
  },
  {
    id: 'blr-lead-010',
    name: 'Zenith CrossFit & Functional Fitness',
    category: 'Gym & Fitness Center',
    nicheId: 'boutique-gyms',
    locality: 'Koramangala',
    zone: 'South',
    address: '5th Block, near Jyoti Nivas College, Koramangala, Bengaluru, Karnataka 560095',
    phone: '+919740112837',
    rawPhone: '097401 12837',
    rating: 4.9,
    reviewsCount: 130,
    website: 'https://instagram.com/zenithcrossfitblr',
    websiteStatus: 'SOCIAL_ONLY',
    googleMapsUrl: 'https://maps.google.com/?q=Zenith+Crossfit+Koramangala+Bangalore',
    opportunityScore: 93,
    crmStatus: 'NEW',
    notes: 'Trendy fitness studio. Needs membership tier comparison & free trial pass booking funnel.',
    createdAt: new Date().toISOString()
  },
  {
    id: 'blr-lead-011',
    name: 'Cadence Academy of Music & Performing Arts',
    category: 'Coaching Academy',
    nicheId: 'coaching-institutes',
    locality: 'Hebbal',
    zone: 'North',
    address: 'Bellary Road, Kempapura, Hebbal, Bengaluru, Karnataka 560024',
    phone: '+919901456789',
    rawPhone: '099014 56789',
    rating: 4.7,
    reviewsCount: 45,
    website: null,
    websiteStatus: 'NO_WEBSITE',
    googleMapsUrl: 'https://maps.google.com/?q=Cadence+Music+Academy+Hebbal+Bangalore',
    opportunityScore: 87,
    crmStatus: 'NEW',
    notes: 'Music academy with instrumental courses. Offer student enrollment & video portfolio site.',
    createdAt: new Date().toISOString()
  },
  {
    id: 'blr-lead-012',
    name: 'ActiveCare Physio & Sports Rehabilitation',
    category: 'Physiotherapy Clinic',
    nicheId: 'physiotherapy',
    locality: 'Sarjapur Road',
    zone: 'South',
    address: 'Kaikondrahalli, Sarjapur Main Road, Bengaluru, Karnataka 560035',
    phone: '+919632881902',
    rawPhone: '096328 81902',
    rating: 4.8,
    reviewsCount: 76,
    website: null,
    websiteStatus: 'NO_WEBSITE',
    googleMapsUrl: 'https://maps.google.com/?q=ActiveCare+Physio+Sarjapur+Road+Bangalore',
    opportunityScore: 94,
    crmStatus: 'NEW',
    notes: 'Surrounded by large apartment complexes on Sarjapur Road. Pitch home-visit scheduling site.',
    createdAt: new Date().toISOString()
  }
];

module.exports = { SEED_LEADS };
